codecovVersion: latest-stable

# web deployment resources
web:
  image: codecov/enterprise-web
  replicas: 2
  annotations: {}
  resources:
    limits:
      cpu: 1000m
      memory: 2048M
    requests:
      cpu: 150m
      memory: 128M

api:
  image: codecov/enterprise-api
  annotations: {}
  replicas: 2
  port: 8000
  servicePort: 8000
  resources:
    limits:
      cpu: 1000m
      memory: 2048M
    requests:
      cpu: 250m
      memory: 256M

# worker deployment resources
worker:
  image: codecov/enterprise-worker
  replicas: 2
  annotations: {}
  resources:
    limits:
      cpu: 3000m # limit to number of CPU cores available if possible (1000 * cores)
      memory: 4096M
    requests:
      cpu: 500m
      memory: 1024M

# optional tags which are set as annotations on the web and worker deployments
tags:
  application: codecov

# these are intended to be overridden via --set-file.  They should not be set
# in values.yaml
codecovYaml: ""
scmCaCert: null
